### ISSUE TITLE
Missing data? IPhone 6 boardview 

### ISSUE THREAD

**Issue by HighOnTek** [Phoneboard/phoneboard.github.io#2]
Nice work Guido with the app, I'll be sure to donate.
This evening while working on a touch issue, I noticed that J2118 Pin #1 shows visually as connected to C2103, but not FL2159 (no red pad).

However if you select FL2159 it lights up both Pin 1 and C2103... yet still doesn't go red itself.
Is that a bug, missing date... or working as expected?

**Comment by guidopola** [comment]
Hi! Thank you for the report, this is indeed a bug.
I added it to the list [here](https://github.com/Phoneboard/phoneboard/issues/35).

Please if you find any other issue report it [here](https://github.com/Phoneboard/phoneboard/issues/)
